/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BooleanProperty: typeof import('./src/components/BooleanProperty.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    DeliberativeRule: typeof import('./src/components/DeliberativeRule.vue')['default']
    FrameComponent: typeof import('./src/components/FrameComponent.vue')['default']
    IntegerProperty: typeof import('./src/components/IntegerProperty.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemChart: typeof import('./src/components/ItemChart.vue')['default']
    ItemListItem: typeof import('./src/components/ItemListItem.vue')['default']
    ItemProperty: typeof import('./src/components/ItemProperty.vue')['default']
    ItemPublisher: typeof import('./src/components/ItemPublisher.vue')['default']
    LogInDialog: typeof import('./src/components/LogInDialog.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    ReactiveRule: typeof import('./src/components/ReactiveRule.vue')['default']
    RealProperty: typeof import('./src/components/RealProperty.vue')['default']
    RegisterDialog: typeof import('./src/components/RegisterDialog.vue')['default']
    RuleListItem: typeof import('./src/components/RuleListItem.vue')['default']
    Solver: typeof import('./src/components/Solver.vue')['default']
    SolverGraph: typeof import('./src/components/SolverGraph.vue')['default']
    SolverListItem: typeof import('./src/components/SolverListItem.vue')['default']
    SolverTimelines: typeof import('./src/components/SolverTimelines.vue')['default']
    StringProperty: typeof import('./src/components/StringProperty.vue')['default']
    SymbolProperty: typeof import('./src/components/SymbolProperty.vue')['default']
    TaxonomyGraph: typeof import('./src/components/TaxonomyGraph.vue')['default']
    Type: typeof import('./src/components/Type.vue')['default']
    TypeListItem: typeof import('./src/components/TypeListItem.vue')['default']
  }
}
