services:
  coco-db:
    container_name: coco-db
    image: mongo
    restart: always
    networks:
      - coco-net

  coco-duckling:
    container_name: coco-duckling
    image: rasa/duckling
    restart: always
    networks:
      - coco-net

  coco-transformer:
    container_name: coco-transformer
    image: rasa/rasa:3.6.20-full
    restart: always
    networks:
      - coco-net
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api

  coco-system:
    container_name: coco
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - coco-net
    depends_on:
      - coco-db
    restart: always
    environment:
      - MONGODB_HOST=coco-db
      - TRANSFORMER_HOST=coco-transformer      

networks:
  coco-net: