/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BooleanPublisher: typeof import('./src/components/BooleanPublisher.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    IntPublisher: typeof import('./src/components/IntPublisher.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemChart: typeof import('./src/components/ItemChart.vue')['default']
    ItemListItem: typeof import('./src/components/ItemListItem.vue')['default']
    ItemPublisher: typeof import('./src/components/ItemPublisher.vue')['default']
    MultipleSymbolPublisher: typeof import('./src/components/MultipleSymbolPublisher.vue')['default']
    RealPublisher: typeof import('./src/components/RealPublisher.vue')['default']
    SingleSymbolPublisher: typeof import('./src/components/SingleSymbolPublisher.vue')['default']
    StringPublisher: typeof import('./src/components/StringPublisher.vue')['default']
    TaxonomyGraph: typeof import('./src/components/TaxonomyGraph.vue')['default']
    Type: typeof import('./src/components/Type.vue')['default']
    TypeListItem: typeof import('./src/components/TypeListItem.vue')['default']
  }
}
